/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiUiRouteImport } from './routes/api/ai-ui'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiUiRoute = ApiAiUiRouteImport.update({
  id: '/api/ai-ui',
  path: '/api/ai-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai-ui' | '/api/public/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai-ui' | '/api/public/sync'
  id: '__root__' | '/' | '/api/ai-ui' | '/api/public/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiUiRoute: typeof ApiAiUiRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-ui': {
      id: '/api/ai-ui'
      path: '/api/ai-ui'
      fullPath: '/api/ai-ui'
      preLoaderRoute: typeof ApiAiUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiUiRoute: ApiAiUiRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
